Issue 5
gorushkin/backend-project-lvl4 pull request #14
Opened 2021-02-03 19:05 UTC by gorushkin

Доделал статусы, написал тесты

2021-02-04 05:50 UTC, foofaev requested changes

2021-02-04 05:50 UTC, foofaev commented on __tests__/statuses.test.js
> +    const responseSignIn = await app.inject({
мы же это в функцию убрали

2021-02-04 05:50 UTC, foofaev commented on __tests__/statuses.test.js
> +    // console.log('response: ', response);
кажется, от разработки осталось

2021-02-04 05:50 UTC, foofaev commented on __tests__/statuses.test.js
> +    expect(deletedStatus).toEqual(undefined);
https://jestjs.io/docs/en/expect#tobeundefined
expect.to.be.undefied чуть лучше читается

2021-02-04 05:50 UTC, foofaev commented on server/routes/statuses.js
> +      const user = new app.objection.models.user();
хм, не баг ли это?

2021-02-04 05:50 UTC, foofaev commented on server/routes/statuses.js
> +          reply.render('/statuses/new', { user: req.body.data, errors: data });
тоже похоже на баг

2021-02-04 05:50 UTC, foofaev commented on server/routes/statuses.js
> +      '/statuses/:id/edit',
этот путь, кажется. не тестировали

2021-02-05 18:58 UTC, foofaev requested changes

2021-02-05 18:58 UTC, foofaev commented on __tests__/helpers/index.js
> +  const tasks = await knex('statuses').insert(getFixtureData('statuses.json'));
без https://knexjs.org/#Builder-returning там будет пусто. да и переменные не используются. тут линтер упасть должен был

2021-02-06 17:45 UTC, gorushkin commented on __tests__/helpers/index.js
> +  const tasks = await knex('statuses').insert(getFixtureData('statuses.json'));
Эт я пытался вывести в console.log что-то оттуда, да и забыл потом убрать )

2021-02-09 21:49 UTC, foofaev approved these changes

2021-02-09 21:49 UTC, merged