Issue 13
gorushkin/backend-project-lvl4 pull request #16
Opened 2021-02-06 17:46 UTC by gorushkin

2021-02-07 09:37 UTC, foofaev requested changes

2021-02-07 09:37 UTC, foofaev commented on __tests__/users.test.js
> +import { it } from '@jest/globals';
не ннада нам это

2021-02-07 09:37 UTC, foofaev commented on __tests__/users.test.js
> +    const cookie = await getCookie(app, testData.users.existing);
мы разве перед каждым тестом не собираем куку?

2021-02-07 09:37 UTC, foofaev commented on server/index.js
> +  app.decorate('checkIfUSerCanEditProfile', (request, reply, done) => {
USer, видимо, "S" должна быть меньше

2021-02-07 14:19 UTC, gorushkin commented on __tests__/users.test.js
> +import { it } from '@jest/globals';
лезут и лезут....
Когда надо VS Code редко импортит, а когда не надо - постоянно норовит засунуть подобное.
Глаз да глаз нужен!!!

2021-02-09 21:45 UTC, foofaev approved these changes

2021-02-09 21:46 UTC, merged