Issue 6
gorushkin/backend-project-lvl4 pull request #17
Opened 2021-02-13 18:38 UTC by gorushkin

2021-02-14 10:02 UTC, foofaev requested changes
Очень круто, что удалось разобраться с джоинами. Это очень полезно и точно не зря. Но надо будет заменить их на встроенную абстракцию

2021-02-14 10:02 UTC, foofaev commented on __tests__/tasks.test.js
> +  it('Get tasks create page work', async () => {
непонятное предложение

2021-02-14 10:02 UTC, foofaev commented on __tests__/tasks.test.js
> +  it('Get tasks edit page work', async () => {
тоже

2021-02-14 10:02 UTC, foofaev commented on __tests__/tasks.test.js
> +    const updatedTask = await models.task.query().findOne({ id });
findById?

2021-02-14 10:02 UTC, foofaev commented on __tests__/tasks.test.js
> +    const undeletedtask = await models.task.query().findOne({ id });
camelCase тут отвалился

2021-02-14 10:02 UTC, foofaev commented on __tests__/tasks.test.js
> +  it('Can not delete status with that belongs to anothet user', async () => {
удаляется таска же

2021-02-14 10:02 UTC, foofaev commented on server/helpers/index.js
> +const getTask = async (app, id) => {
хм, конечно, хорошо, что сложный код вынесен в отдельную функцию. Но в данном случае сложность необязательная.
У нашей ORM есть такой метод - https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphjoined

Но даже если бы этого метода не было бы, то лучше методы доступа к орм хранить там же, где все остальные методы доступа к орм. В данном случае методы у нас в классе Task. Поэтому такой метод стоило бы там определить. Это нужно для того, чтобы изолировать методы доступа к базе данных в рамках одной абстракции. Это значительно упростит рефакторинг (например, нам надо одно поле поменять, и мы поменяем его в модели. а тут забудем)

2021-02-14 10:02 UTC, foofaev commented on server/index.js
> +    const { creatorId } = await app.objection.models.task.query().findOne({ id: request.params.id });
findById?

2021-02-14 10:02 UTC, foofaev commented on server/migrations/20210206205421_create_tasks_table.js
> +    table.boolean('is_complete').default(false);
у нас есть статусы же. зачем нам такой флаг?
более того, стоит всегда уходить от флагов (https://ru.hexlet.io/courses/js-polymorphism/lessons/state/theory_unit)

2021-02-14 10:02 UTC, foofaev commented on server/models/Task.js
> +        isComplete: { type: 'boolean', default: false },
написал про это поле выше

2021-02-14 10:02 UTC, foofaev commented on server/models/Task.js
> +    const Status = require('./Status');
вот эти две строки не проходят линтер

2021-02-14 10:02 UTC, foofaev commented on server/routes/tasks.js
> +        .innerJoin('users as executor', 'executor.id', 'tasks.executorId');
писал про это выше. https://vincit.github.io/objection.js/api/query-builder/eager-methods.html#withgraphjoined

2021-02-14 10:02 UTC, foofaev commented on server/routes/tasks.js
> +            throw Error('There is no task with such parametrs');
было бы хорошо использовать не голые ошибки, а заранее подготовленные со статус кодами. Они у нас уже есть https://github.com/fastify/fastify-sensible

2021-02-14 10:02 UTC, foofaev commented on server/routes/users.js
> +          if (usersTasks) throw new Error('Нельяз удалить пользователя');
ошибка в данном случае будет мало информативна. может, лучше просто флеш красный повесить с описанием?

2021-02-14 10:02 UTC, foofaev commented on server/routes/users.js
> +          if (usersTasks) throw new Error('Нельяз удалить пользователя');
еще, видимо, нужно в статусах тоже такую проверку добавить

2021-02-14 10:02 UTC, foofaev commented on server/index.js
> +  app.decorate('checkIfUserCanDeleteTask', async (request, reply, done) => {
хм, не совсем соответствует название функции ее смыслу.
checkIfUserCreatedTask

2021-02-16 15:39 UTC, foofaev requested changes
Еще чуть-чуть! Все очень хорошо

2021-02-16 15:39 UTC, foofaev commented on server/models/Task.js
> +      .withGraphJoined('status');
нам доступна такая магия: withGrapJoined('[creator, executor, status]')

2021-02-16 15:39 UTC, foofaev commented on server/routes/tasks.js
> +        .withGraphJoined('status');
писал про шорткат выше. в целом странно, что там сложный запрос мы убрали в класс, а тут нет. в целом тот метод из класса можно и убрать, если не страшно опечататься в списке джоинов. если страшно, то можно какой-то общий метод туда выкинуть, или даже не метод, а список джоинов, которые тут уже будем забирать

2021-02-16 15:39 UTC, foofaev commented on server/routes/tasks.js
> +      const statuses = await app.objection.models.status.query();
Promise.all тут просится

2021-02-16 15:39 UTC, foofaev commented on server/views/tasks/details.pug
> +        .col Исполнитель
вообще говоря, мы стараемся тексты убрать в i18 и забирать их оттуда. сейчас как-то половинчато, часть тут, часть там

2021-02-16 15:39 UTC, foofaev commented on server/views/tasks/details.pug
> +        .col Исполнитель
кнопок это тоже касается

2021-02-16 15:39 UTC, foofaev commented on server/routes/tasks.js
> +            throw app.httpErrors.notFound('There is no task with such parametrs');
бросаем внутри try catch. сами же ловим. не сработает скорей всего. флеш + редирект будут более информативны

2021-02-16 15:39 UTC, foofaev commented on server/routes/tasks.js
> +        const statuses = await app.objection.models.status.query();
promise.all просится очень

2021-02-16 17:44 UTC, gorushkin commented on server/models/Task.js
> +      .withGraphJoined('status');
ОГО!!!!! Это офигенно!!!!!!
Черт, сколько там еще всего есть непонятного =((

2021-02-17 19:58 UTC, foofaev requested changes
Еще чуть-чуть и перфекто

2021-02-17 19:58 UTC, foofaev commented on server/routes/tasks.js
> +        new app.objection.models.task(),
синхронный метод нет смысла в промис

2021-02-17 19:58 UTC, foofaev commented on server/routes/tasks.js
> +        await app.objection.models.status.query(),
await тут не нужен в каждом методе.
сейчас получается, что в await, который внутри Promise.all, вызывается до того, как вызвался promise.all. Наш promise.all бессмысленный

2021-02-17 19:58 UTC, foofaev commented on server/routes/tasks.js
> +          await app.objection.models.status.query(),
про await то же, что выше

2021-02-18 07:27 UTC, gorushkin commented on server/routes/tasks.js
> +        new app.objection.models.task(),
Александр, я тормоооз)))

2021-02-18 07:28 UTC, gorushkin commented on server/routes/tasks.js
> +        await app.objection.models.status.query(),
И тут тоже сглупил =(

2021-02-19 09:07 UTC, foofaev requested changes

2021-02-19 09:07 UTC, foofaev commented on server/routes/tasks.js
> +            .withGraphJoined('[creator, executor, status]'),
это тут разве было? мы же ниже уже собираем всех юзеров + статусы. можно оттуда забрать и не грузить лишний раз

2021-02-19 20:46 UTC, foofaev approved these changes

2021-02-19 20:46 UTC, merged

2021-02-19 20:46 UTC, foofaev commented
теперь перфекто!