Issue 7
gorushkin/backend-project-lvl4 pull request #20
Opened 2021-02-23 08:37 UTC by gorushkin

2021-02-24 10:04 UTC, foofaev requested changes

2021-02-24 10:04 UTC, foofaev commented on server/routes/tasks.js
> +  return labelIdFormatMatching[typeof labels](labels);
маппинг - это хорошо. но тут дефолтного кейса не хватает, потому что надеяться на typeof не очень надежно

но можно вообще проще
[labels].flatten().map(...)

2021-02-24 10:04 UTC, foofaev commented on server/routes/tasks.js
> +const getLabelIdList = (labels = []) => {
тут скорее labelIds ? а не метки целиком

2021-02-24 10:04 UTC, foofaev commented on server/routes/tasks.js
> +              task.$relatedQuery('labels', trx).unrelate(),
если таска успеет удалиться, то unrelate не сработает. Стоит это делать по очереди и добавить тесты

2021-02-24 10:04 UTC, foofaev commented on server/views/tasks/edit.pug
> +            option(value=label.id, selected= checkLabel(label.id, taskLabelId))= label.name
у нас тут абстракция течет. Работу с конкретными данными, переданными в форму лучше оставить в миксине. Стоит добавить недостающие:
```
    +input(task, 'name', errors)(type="text")
    +textarea(task, 'description', errors)(rows="3")
    +select(task, 'statusId', errors, statuses)
    +select(task, 'executorId', errors, users)
```

Чтобы, когда мы поменяем что-то в бд, нам нужно было только миксин поменять, а не все темплейты

2021-02-24 10:04 UTC, foofaev commented on server/views/tasks/edit.pug
> +            option(value=label.id, selected= checkLabel(label.id, taskLabelId))= label.name
Ну и то же самое относится к другим темплейтам

2021-02-24 17:40 UTC, gorushkin commented on server/routes/tasks.js
> +  return labelIdFormatMatching[typeof labels](labels);
О, сколько нам открытий чудных
Готовят просвещенья дух ... и т.д) Спасибо!

2021-02-26 08:43 UTC, foofaev requested changes
Все очень хорошо!
Немного порефакторим только

2021-02-26 08:43 UTC, foofaev commented on __fixtures__/testData.json
> +    "withlabelsTask": {
получится testData.tasks.withLabelsTask?
может, будем придерживаться одного вида именования, сделаем как остальные. testData.tasks.existingWithLabels

2021-02-26 08:43 UTC, foofaev commented on __tests__/tasks.test.js
> +  it('add relations', async () => {
мы тут конкретно labels проверяем

2021-02-26 08:43 UTC, foofaev commented on server/routes/labels.js
> +        } catch ({ data }) {
на самом деле,  не уверен, что кетч тут нужен. если удаление отвалилось, то, возможно, там какая-то внутренняя проблема. а мы о ней даже не узнаем.

2021-02-26 08:43 UTC, foofaev commented on server/routes/tasks.js
>          req.flash('error', i18next.t('flash.task.create.error'));
в кетче не хватает данных для пути tasks/new. Мы же туда еще должны закидывать всех юзеров, статусы, лейблы

2021-02-26 08:43 UTC, foofaev commented on server/routes/tasks.js
> +          const insertedTask = await app.objection.models.task.query(trx).insert(task);
не то, чтобы это сильно важно было, но мы учимся, поэтому напишу.
Есть метод, который позволит все разом положить в базу - https://vincit.github.io/objection.js/guide/query-examples.html#graph-inserts

(смотри relate: ['labels'])

2021-02-26 08:43 UTC, foofaev commented on server/routes/tasks.js
> +        }));
так-то это фронтовая логика совсем. бэкенд знать о ней не должен. иначе изменения на фронте будут тащить за собой изменения на бэке.

2021-02-26 08:43 UTC, foofaev commented on server/routes/tasks.js
> +          task.$relatedQuery('labels'),
если забирать таску по findById().withGraphJoined, то этот вызов не нужен

2021-02-26 08:43 UTC, foofaev commented on server/routes/tasks.js
> +          });
Тут все хорошо. Но опять же стоит знать о методе https://vincit.github.io/objection.js/guide/query-examples.html#graph-upserts

Тут можно использовать upsertGraph + опции relate: true, unrelate: true, noDelete: true,
НО тут у нас крайне простая логика. Поэтому можно использовать upsertGraph. В более сложных случаях лучше его избегать

2021-02-26 08:43 UTC, foofaev commented on server/views/mixins/forms.pug
> +- const getItemName = (item) => { const result = item.name ? item.name : `${item.firstname} ${item.lastname}`; return result; }
мы этот хак делаем только для юзеров же? можно в классе юзера сделать геттер
get name() {
  return `this.firstName this.lastName`

2021-02-26 18:51 UTC, gorushkin commented on __tests__/tasks.test.js
> +  it('add relations', async () => {
блин, сначала они сильно были на тасках завязаны, потом я их переписал, а в лейблы не перенес, забыл (

2021-02-26 19:42 UTC, gorushkin commented on server/routes/tasks.js
> +          const insertedTask = await app.objection.models.task.query(trx).insert(task);
это какое-то читерство!!!!! =)

2021-02-28 07:08 UTC, foofaev requested changes

2021-02-28 07:08 UTC, foofaev commented on __tests__/labels.test.js
> +      await models.task.query().findById(id).withGraphJoined('labels')
а тут не лишний запрос? 
findOne().withGraphJoined()

2021-02-28 07:08 UTC, foofaev commented on server/models/User.js
> +    return `${this.firstname} ${this.lastname}`;
все-таки я имел ввиду прямо геттер. если его добавить, то обращатья к имени можно будет просто user.name. Тогда функции на классах остальных не нужны, потому что у них уже есть name
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/get

get name() {
  return 
}

2021-02-28 07:08 UTC, foofaev commented on server/routes/tasks.js
> +        await app.objection.models.task.query().insertGraph([{ ...task, labels: labelIds }], {
модифицирующий метод, который еще и другие колонки затрагивает хорошо бы в транзакцию завернуть

2021-02-28 07:08 UTC, foofaev commented on server/routes/tasks.js
> +          await app.objection.models.task.query().upsertGraph(
вот тут надо быть осторожными. мы не ограничиваем граф на то, какие связи можно менять, поэтому можно убить лишнее. Нужно добавить тесты на обновление всех полей вместе и по отдельности

2021-02-28 07:08 UTC, foofaev commented on __tests__/tasks.test.js
>      expect(anotherTask).toMatchObject(undeletedTask);
У нас в тесте на метод PATCH всего один тест и он проверяет только, что имя изменилось. Давай добавим PATCH на разные связи, в том числе статусы, лейблы, создателя с исполнителем. И будем проверять,что лишнее не изменилось

2021-03-01 20:34 UTC, foofaev commented on __tests__/tasks.test.js
> +
что-то в тестах отличается только data + expected. давай в tests.each завернем, так жить проще станет

2021-03-02 10:27 UTC, foofaev approved these changes
Прекрасно!

2021-03-02 10:27 UTC, merged